"""empty message

Revision ID: 71d7772e59f7
Revises: 919a1fe394c4
Create Date: 2016-07-07 23:03:19.869095

"""

# revision identifiers, used by Alembic.
revision = '71d7772e59f7'
down_revision = '919a1fe394c4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
