"""empty message

Revision ID: c48bd52d6615
Revises: f4efa5ae67c7
Create Date: 2016-08-21 22:37:20.690490

"""

# revision identifiers, used by Alembic.
revision = 'c48bd52d6615'
down_revision = 'f4efa5ae67c7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
